### ISSUE TITLE
Cara menambahkan Background ke Dropdown gimana ?

### ISSUE THREAD

**Issue by mzcoder-hub** [elhakimyasya/thumbs#2]
Cara menambahkan Background ke Dropdown gimana ? saya udah desain sudah sana kasih nama cuman gak masuk di dropdown mohon bantinganya

**Comment by elhakimyasya** [comment]
Silahkan tambahkan gambar tersebut ke dalam folder `/image`. Dan tautkan gambar url gambar kedalam file `index.html`.

**Comment by mzcoder-hub** [comment]
Sudah ditambahkan di folder image gan tapi di dropdown sudah saya link juga, waktu saya pilih backgroundnya gk muncul padahal formatnya sana

**Comment by elhakimyasya** [comment]
> 
> 
> Sudah ditambahkan di folder image gan tapi di dropdown sudah saya link juga, waktu saya pilih backgroundnya gk muncul padahal formatnya sana

1. Tambahkan option dengan valuenya seperti pada baris [#236](https://github.com/elhakimyasya/thumbs/blob/f9b5bb600d0c2c6ee2132d7dd55415f86d2b89ad/index.html#L236) 
2. Tambahkan gambar dengan format yang sama ke dalam folder [/image](https://github.com/elhakimyasya/thumbs/tree/master/images);
3. Tambahkan style baru seperti pada baris [#220](https://github.com/elhakimyasya/thumbs/blob/f9b5bb600d0c2c6ee2132d7dd55415f86d2b89ad/style.css#L220).

**Comment by mzcoder-hub** [comment]
Nah gitu gan paham saya wkekw gk kepikiran kalau di dalem css
